// <auto-generated />
namespace Thegioisticker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init_thegioisticker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_thegioisticker));
        
        string IMigrationMetadata.Id
        {
            get { return "202010090916171_init_thegioisticker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
